GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJpYXQiOjE2NDI1MDI0NTIsImV4cCI6MTY0MjUwMjUxMn0.3iE9rJHyZjpRhBVnQvrxtY8ct6Vbrg9HO-GwzBMYFoI

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "Hello",
    "email" : "Hello@lol",
    "password" : "Hello"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{    
    "email" : "Hello@lol",
    "password" : "Hello"
}
###
GET http://localhost:3000/habits
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJpYXQiOjE2NDI2MDQ5ODh9.zTcCbiPEZSM2eeH8tcaPnttfeAUaxKPjd0hPJkSFiZg

###
GET http://localhost:3000/habitplans
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJ1c2VySUQiOjMsImlhdCI6MTY0MjYyNDY5Mn0.I7urov_O62KCcXFkMe4KntlSUSFD7CfC9-ihxukZOYc

# INSERT INTO habit_plans VALUES(6, 3,1, '2022-01-10','9999-12-31', 2);