GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJpYXQiOjE2NDI1MDI0NTIsImV4cCI6MTY0MjUwMjUxMn0.3iE9rJHyZjpRhBVnQvrxtY8ct6Vbrg9HO-GwzBMYFoI

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "Hello",
    "email" : "Hello@lol",
    "password" : "Hello"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{    
    "email" : "Hello@lol",
    "password" : "Hello"
}

###
GET http://localhost:3000/habits
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJpYXQiOjE2NDI1ODc2ODh9.gb-gTLKuKZi1Wx_SvDYBEsUdu1tCy_WCC77sbUM0V0I

{
    "email": "Hello@lol",
    "date":"2022-01-11"

}


###

GET http://localhost:3000/habitplans?date=2022-01-11
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJ1c2VySUQiOjMsImlhdCI6MTY0MjY4MDAxOX0.9qI8mPWnHTxDCC6eVEs9uE7nZSAZhJQ0Mbav03ZgWa0

{
    "email":"Hello@lol"
}

# INSERT INTO habit_plans VALUES(6, 3,1, '2022-01-10','9999-12-31', 2);


# INSERT INTO habit_plans VALUES(6, 3,1, '2022-01-10','9999-12-31', 2);
###

POST http://localhost:3000/habitplans
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJpYXQiOjE2NDI1NjAzODV9.2YHkjqZNqir1Ko7Bc0MF1qm1gSwfnvn1mdkio87rpyI

{
    "user_id":3,
    "begin_date":"2022-01-10",
    "end_date":"2022-01-20",
    "frequency":3,
    "habit_id":2

}

###

PATCH http://localhost:3000/habitplans/update
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJpYXQiOjE2NDI1NjAzODV9.2YHkjqZNqir1Ko7Bc0MF1qm1gSwfnvn1mdkio87rpyI

{   
    "end_date":"2022-01-31",
    "id": 2
    
}

###

GET http://localhost:3000/habitplans/1
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJ1c2VySUQiOjMsImlhdCI6MTY0MjY3OTYyOX0.g7ImgKXM8NW2u4Av0y-SBfsEpAjgoykwLZfvIkQ4zPM

{
    "start_date":"2022-01-11",
    "end_date":"2022-01-19"
}
###
POST http://localhost:3000/habitfacts
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwiZW1haWwiOiJIZWxsb0Bsb2wiLCJ1c2VySUQiOjMsImlhdCI6MTY0MjY3OTYyOX0.g7ImgKXM8NW2u4Av0y-SBfsEpAjgoykwLZfvIkQ4zPM

{
    "hplan_id":10
}